vim.o.confirm = true
vim.o.cursorline = true
vim.o.listchars = 'tab:» ,eol:¶,nbsp:␣,trail:•,extends:⟩,precedes:⟨'
vim.o.modeline = true
vim.o.relativenumber = true
vim.o.ruler = true
vim.o.scrolloff = 8
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.visualbell = true
vim.o.wildmode = 'longest:full,full'
